# ================================
# DanDon01's Tech Blog Configuration
# ================================

# Site Settings
title: "DanDon01's GitHub Blog"
email: "" # Optional, or use a contact form instead.
description: >-
  Sharing my projects, experiments, and insights into the world of 
  technology, coding, and electronics. Follow along for Python scripts, 
  Raspberry Pi projects, and 3D printing builds.
baseurl: "" # Leave blank for root URL
url: "https://DanDon01.github.io" # Your live site URL

header_pages:
  - projects.md    # Projects page
  - archive.md     # Blog archive
  - about.md       # About page

# Social Links & Contact
github_username: DanDon01
rss: true # Enables RSS feed link for readers
footer_links:
  - title: "GitHub"
    url: "https://github.com/DanDon01"
    icon: "github"
  - title: "RSS Feed"
    url: "/feed.xml"
    icon: "rss"
  - title: "Email Me"
    url: "mailto:contact@dandon01.dev"
    icon: "mail"

# Theme Settings
theme: minima
minima:
  skin: dark # Ensure dark theme is enabled

# Blog Customisation
show_excerpts: true # Show previews of posts on the homepage
paginate: 5 # Number of posts to display per page

# SEO and Metadata
author: "DanDon01"
keywords: >-
  Python projects, Raspberry Pi, 3D printing, coding blog, tech tutorials,
  electronics, automation
language: "en"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Exclude Unnecessary Files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

# Footer Text (Optional custom note)
footer_text: >-
  Built with ❤️ using GitHub Pages and Jekyll. Powered by coffee and curiosity.

footer_links:
  - title: "RSS Feed"
    url: "/feed.xml"
    icon: "rss"

# Extra Touch: Build Timestamp for Debugging
build_timestamp: "{{ site.time | date: '%Y-%m-%d %H:%M:%S' }}"
