# Welcome to DanDon01's Blog Config
# =================================


# Site Settings
title: "DanDon01's Tech Blog"
email: ""
description: >-
  A space where I share my projects, thoughts, and experiments in tech, 
  coding, and life. Follow along for cool Python scripts and electronics builds.
baseurl: "" # Leave blank for root URL
url: "https://DanDon01.github.io" # Live site URL

# Social Links
X_username: AI_TechnoKing
github_username:  DanDon01
linkedin_username: dandon01

# Theme Settings
theme: minima
minima:
  skin: dark

# Customisation
show_excerpts: true # Show post previews on homepage
paginate: 5 # Number of posts per page

# Build Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# SEO and Site Metadata
author: "DanDon01"
keywords: "tech blog, Python projects, 3D printing, Raspberry Pi, coding tutorials"
language: "en"

# Header/Footer Customisation
footer_links:
  - title: "GitHub"
    url: "https://github.com/DanDon01"
    icon: "github"


# Navigation (Custom Menu Links)
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "About"
    url: "/about"
  - title: "Contact"
    url: "/contact"

# Exclude Unnecessary Files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# A Techy Touch: Build Information
build_timestamp: "{{ site.time | date: '%Y-%m-%d %H:%M:%S' }}"
